ember g component telco-forms/incident-management-form
ember g component telco-forms/information-security-form
ember g component telco-forms/request-fulfilment-form
ember g component telco-forms/release-management-form
ember g component telco-forms/capacity-management-form
ember g component telco-forms/problem-management-form
ember g component telco-forms/service-level-management-form
ember g component telco-forms/change-management-form
ember g component telco-forms/configuration-management-form
ember g component telco-forms/continuity-management-form
ember g component telco-forms/event-management-form
ember g component telco-forms/availability-management-form
ember g component telco-forms/demand-management-form
ember g component telco-forms/knowledge-management-form
