# .circleci/config.yml
defaults: &defaults
  docker:
    - image: circleci/node:6-browsers
      environment:
        JOBS: 2
  working_directory: ~/buy-nsw-front

version: 2
jobs:
  checkout_code:
    <<: *defaults
    steps:
      - checkout
      - persist_to_workspace:
          root: .
          paths:
            - .

  install_dependencies:
    <<: *defaults
    steps:
      - attach_workspace:
          at: .
      - restore_cache:
          keys:
            - v1-deps-{{ .Branch }}-{{ checksum "package-lock.json" }}
            - v1-deps-{{ .Branch }}-
            - v1-deps-
      - run:
          name: NPM Install
          command: npm install
      - save_cache:
          key: v1-deps-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - persist_to_workspace:
          root: .
          paths:
            - .

  lint_js:
    <<: *defaults
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Lint JS
          command: npm run lint:js

  run_tests:
    <<: *defaults
    steps:
      - attach_workspace:
          at: .
      - run: echo 'export PATH=~/buy-nsw-front/node_modules/.bin:$PATH' >> $BASH_ENV
      - run:
          name: Run Tests
          command: npm test

  deploy_testing:
    <<: *defaults
    steps:
      - attach_workspace:
          at: .
      - run: echo 'export PATH=~/buy-nsw-front/node_modules/.bin:$PATH' >> $BASH_ENV
      - run:
          name: Deploy
          command: ember deploy testing --activate=true --verbose

  deploy_staging:
    <<: *defaults
    steps:
      - attach_workspace:
          at: .
      - run: echo 'export PATH=~/buy-nsw-front/node_modules/.bin:$PATH' >> $BASH_ENV
      - run:
          name: Deploy
          command: ember deploy staging --activate=true --verbose

workflows:
  version: 2
  test_and_deploy:
    jobs:
      - checkout_code
      - install_dependencies:
          requires:
            - checkout_code
      - lint_js:
          requires:
            - install_dependencies
      - run_tests:
          requires:
            - install_dependencies
      - deploy_testing:
          requires:
            - lint_js
#            - run_tests
          filters:
            branches:
              only:
                - /release-.*/
                - testing
      - deploy_staging:
          requires:
            - lint_js
#            - run_tests
          filters:
            branches:
              only:
                - master
                - staging
