import DS from 'ember-data';

export default DS.Model.extend({
  name: DS.attr('string'),
  summary: DS.attr('string'),
  tags: DS.attr(),
  services: DS.attr(),
  level_2_services: DS.attr(),
  website_url: DS.attr('string'),
  linkedin_url: DS.attr('string'),
  twitter_url: DS.attr('string'),
  facebook_url: DS.attr('string'),
  instagram_url: DS.attr('string'),
  contact_first_name: DS.attr('string'),
  contact_last_name: DS.attr('string'),
  contact_phone: DS.attr('string'),
  contact_email: DS.attr('string'),
  representative_first_name: DS.attr('string'),
  representative_last_name: DS.attr('string'),
  representative_phone: DS.attr('string'),
  representative_email: DS.attr('string'),
  abn: DS.attr('string'),
  public_address: DS.attr(),
  receivership: DS.attr('boolean'),
  receivership_details: DS.attr('string'),
  investigations: DS.attr('boolean'),
  investigations_details: DS.attr('string'),
  legal_proceedings: DS.attr('boolean'),
  legal_proceedings_details: DS.attr('string'),
  insurance_claims: DS.attr('boolean'),
  insurance_claims_details: DS.attr('string'),
  conflicts_of_interest: DS.attr('boolean'),
  conflicts_of_interest_details: DS.attr('string'),
  other_circumstances: DS.attr('boolean'),
  other_circumstances_details: DS.attr('string'),
  awards: DS.attr(),
  accreditations: DS.attr(),
  engagements: DS.attr(),
  no_experience: DS.attr('boolean'),
  local_government_experience: DS.attr('boolean'),
  state_government_experience: DS.attr('boolean'),
  federal_government_experience: DS.attr('boolean'),
  international_government_experience: DS.attr('boolean'),
  documents: DS.attr(),
  updated_at: DS.attr('string')
});
